---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
    exclude_fingerprints: []
  fixme:
    enabled: true
    exclude_fingerprints: []
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrcis/MethodLength:
        enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.rb"
exclude_paths:
  - "**.rvmrc"
  - "**.swp"
  - "**~"

